### ISSUE TITLE
WDL generation - make sure it matches the metaP pipeline

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaPro#25]
Generate metaPro WDL and make sure it matched metaP pipeline. 

metaPro WDL pipeline needs adjusting before it will run correctly matching the Python pipeline. To solve this, WDL code and python scripts will need minor alterations. The end result of the edits should be a running WDL pipeline that generates relevant reports and metadata.

**TODO**
- [x] Adjust ficus_analysis.py script to process correct input
- [x] Adjust WDL to pass to relevant parameters to metadata generation script
- [x] Adjust get_meta_data.py script to process inputs and generate correct output

This feature will be complete when the pipeline processes datasets completely and similar to the python pipeline. This task can be completed this sprint.

**Comment by ssarrafan** [comment]
Hi @picowatt. Any update on this issue? Can this issue be closed today or by Tuesday?

**Comment by picowatt** [comment]
Hello @ssarrafan, this is nearly completed. I'm _aiming_ to close out this today, but by Tuesday might be more likely.

**Comment by ssarrafan** [comment]
> Hello @ssarrafan, this is nearly completed. I'm _aiming_ to close out this today, but by Tuesday might be more likely.

Hi @picowatt is it ok to close this today?  Any links or information you'd like to add to the issue before closing?
